export const areas =  
[
    "6th of October",
    "El-Abbasia",
    "El-Dokki",
    "El-Manyal",
    "El-Giza",
    "حدائق القبة",
    "Heliopolis",
    "El-Maadi",
    "Masr El-Kadima",
    "El-Mokattam",
    "Nasr City",
    "Shoubra",
    "El-Zamalek",
    "Helwan",
    "El-Obour City",
    "West El-Balad",
    "El-Agouza",
    "El-Mohandessin",
    "El-Haram",
    "El-Rehab",
    "El-Shorouk",
    "El-Sheikh Zayed",
    "10th of Ramadan",
    "El-Sayeda Zainab",
    "Boulaq",
    "الزيتون",
    "Ain Shams",
    "New Cairo",
    "Luxor City",
    "Banha",
    "Tanta",
    "Faisal",
    "Hadayek El-Ahram",
    "Ibsheway",
    "Beni Suef City",
    "Mahatet El-Raml",
    "Sporting",
    "El-Amreya",
    "الإبراهيمية",
    "Sidy Gaber",
    "Cleopatra",
    "Smouha",
    "Roshdy",
    "El-Shatby",
    "El-Azarita",
    "Loran",
    "Glym",
    "Saba Basha",
    "Sidy Bishr",
    "Miamy",
    "Victoria",
    "San Stefano",
    "Bulkly",
    "Moharam Bek",
    "كامب شيزار",
    "El-Montazah",
    "Kafr Abdouh",
    "Abou Keir",
    "Zizenia",
    "El-Agamy",
    "Bakos",
    "Bahary",
    "El-Mansheyah",
    "El-Seyouf",
    "Janaklees",
    "Stanley",
    "El-Mansoura",
    "El-Zagazig",
    "Marsa Matrouh",
    "Damietta City",
    "Moustafa Kamel",
    "Madinaty",
    "El-Asafra",
    "Fouad Street",
    "King Mariout",
    "North Coast",
    "El-Werdeyan",
    "Damanhur",
    "Shoubra El-Kheima",
    "Khaldi Street",
    "Jabal Amman",
    "Fifth Circle",
    "Seventh Circle",
    "Bayader Wadi Al Sir",
    "Jabal Al Hussain",
    "Shmeisani",
    "University Street",
    "Abdoun",
    "Al Jubeiha and Abu Nusair",
    "Al Kursi and Al Jandaweel",
    "Dabouq",
    "Dahiyat Al Rasheed",
    "شارع الجاردنز",
    "Khilda",
    "Marj El-hamam",
    "Rabieh",
    "Sports City",
    "Sweifieh and Umm Uthaina",
    "Swelieh",
    "Mahalla",
    "Shibin El-Kom",
    "Menouf",
    "Sadat City",
    "Ashrafieh",
    "Adlieh",
    "Aicha Bakar/Malla",
    "Barbir",
    "Basta",
    "Bchara El Khoury",
    "Clemenceau",
    "الكولا",
    "Downtown",
    "Hamra",
    "Jnah",
    "Kraitem",
    "Manara",
    "Mar Elias",
    "Mazraa",
    "Sodeco",
    "Tallet Khayat",
    "Tariq El Jdideh",
    "Tayouneh",
    "Verdun",
    "Baabda",
    "Borj Al Brajne",
    "Chiyah",
    "الغبيري",
    "Ouzai",
    "Chtoura",
    "Zahle",
    "Baalback",
    "Hermel",
    "Riyak",
    "Taanayel",
    "Saadnayel",
    "Mansourieh",
    "Zalka",
    "Jal El Dib",
    "Dekwaneh",
    "Furn El Chebbak",
    "Hazmieh",
    "Bourj Hammoud",
    "Dbayeh",
    "Byblos",
    "Jounieh",
    "Batroun",
    "Ajaltoun",
    "Aley",
    "Chouf",
    "Khaldeh",
    "Hammana",
    "Al Faisaliyah",
    "Al Shati",
    "Al Ruwais",
    "Al Balad",
    "Al Rawdah ",
    "Al Salamah",
    "Al Hamra",
    "Al Bawadi",
    "الجامعة",
    "Al Marwah",
    "Al Shimaisi",
    "Al Uraija",
    "Al Olaya",
    "Al Malaz",
    "Al Batha",
    "العزيزية",
    "Al Maather",
    "El-Mandara",
    "Assiut city",
    "El-Kattameya",
    "El-Matareya",
    "El-Marg",
    "Dar El-Salam",
    "Mit Ghamr",
    "El-Fayoum city",
    "El-Ismailia city",
    "Menya El-Kamh",
    "Fakous",
    "Imbaba",
    "El-Hawamdeya",
    "El-Badrashin",
    "El-Ayyat",
    "Birket El Sabea",
    "Qalyoub",
    "Tla Al Ali and Madineh Street",
    "Marka",
    "Abdallah Ghosheh Street",
    "Makkeh Street and Um Alsumaaq",
    "Muqablain",
    "Abdali",
    "Istiklal Street and Nuzha",
    "Hashmi and Tabarbour",
    "Dahiet Yasmeen",
    "الأشرفية والوحدات",
    "Al Wiebdeh",
    "Hai Nazzal and Akhdar",
    "Nasser and Manara",
    "Qwaismeh and Abu Alanda",
    "Sahab",
    "Haret Hreik",
    "Beer Al Abd",
    "Beer Hassan",
    "Hay el Solom",
    "Choueifet",
    "Hadath",
    "Saint Therese",
    "Sfeir",
    "Sin El Fil",
    "Horsh Tabet",
    "Sabtyeih",
    "Antelias",
    "Bsalim",
    "Fanar",
    "Bikfaya",
    "Ghazier",
    "Kaslik",
    "Maamltien",
    "Tabarja",
    "Aramoun",
    "Bchamoun",
    "Kabrshmoun",
    "طرابلس",
    "Akkar",
    "Koura",
    "Bsharri",
    "Zgharta",
    "Miniyeh/Danniyeh",
    "Saida",
    "Sour",
    "Nabatieh",
    "Jezzine",
    "Bint Jbeil",
    "Hasbaya",
    "Marjeyoun",
    "El Safa",
    "Al Zahraa",
    "Al Andalus",
    "Al Sulaimaniyah ",
    "King Fahad",
    "Al Worood",
    "Al Maseef",
    "Al Muruj",
    "Al Morsalat",
    "Al Ghadeer",
    "Al Wahah",
    "Al Wadi",
    "Al Sahafa",
    "Al Taawun",
    "Al Nozha",
    "Ishbiliyah",
    "Al Quds",
    "الروضة",
    "Al Izdihar",
    "Qurtubah",
    "Al Hamra",
    "Al Naseem Al Sharqi",
    "Al Naseem Al Gharbi",
    "Al Rawabi",
    "Al Rabwah",
    "Al Rayyan",
    "Al Salam",
    "Al Fayha",
    "Shubra",
    "Al Badiah",
    "Al Suwaidi",
    "Al Shifa",
    "Ghubairah",
    "Manfuhah",
    "Al Wizarat",
    "Al Murabba",
    "Salah Al Din",
    "Fleming",
    "Hadayek Helwan",
    "Hadayek El Maadi",
    "Hurghada City",
    "Port Said City",
    "Port Fouad",
    "Abnub",
    "Dayrout",
    "Manfalut",
    "مدينة السويس",
    "Sohag City",
    "El Minya City",
    "Kafr El sheikh City",
    "kafr El dawar",
    "Kafr El Zayat",
    "Al Faisaliyah",
    "Al Hamra",
    "Al Adamah",
    "Al Mazruiyah",
    "Al Shati",
    "Al Dana",
    "Al Muraikabat",
    "Al Aqrabiyah",
    "Al Buhaira",
    "Al Khobar Al Shamalia",
    "Al Ulaya",
    "Al Hizam Al Thahabi",
    "Al Thuqbah",
    "Esna",
    "Qena City",
    "Zarqa",
    "New Zarqa",
    "Yajouz and Alrusaifa",
    "Sharm El Sheikh City",
    "Al Munsiyah",
    "Al Yarmuk",
    "Al Shuhada",
    "Ghirnatah",
    "Al Rabie",
    "Al Nafal",
    "Al Falah",
    "Al Aqiq",
    "Al Safarat",
    "UM Alhammam",
    "Al Raed",
    "Al Mathar Ash Shamali",
    "Badr",
    "As Sulay",
    "Al Mashael",
    "Namar",
    "Al Nadheem",
    "Mishrifah",
    "Al Mohammadiyyah",
    "Takhassusi",
    "Al Sanabel",
    "Al khaleej",
    "Al Marwah",
    "Al Janadriyyah",
    "Al Yasmin",
    "Al Narjis",
    "Al Malqa",
    "Hittin",
    "Al Nahdah",
    "Okaz",
    "Dhahrat Laban",
    "Laban",
    "Wadi Laban",
    "Al Naeem",
    "Al Nahda",
    "Al Bsateen",
    "Al Muhamdeya",
    "Al Naseem",
    "Al Fayhaa",
    "Al Sulymaniya",
    "Al Khaldiya",
    "Tuwaiq",
    "As Saadah",
    "Al Mughrizat",
    "Al Mutamarat",
    "Irqah",
    "Az Zahrah",
    "An Nuzhah",
    "الرحاب",
    "Bani Malik",
    "Al Rawabi",
    "Al Hamadaniyyah",
    "Obhur Al Shamaliyah",
    "Obhur Al Janoobiyah",
    "Al Nadwa",
    "Ad Diriyah",
    "AL Umrah Al Jadidah",
    "An Nawwariyyah",
    "AL Buhayrat",
    "Al Tanim",
    "Al Kakiyyah",
    "Al Khalidiya",
    "Al Shoqiyah",
    "Batha Quraish",
    "As safa",
    "Ar rawdah",
    "As Suways",
    "Sabya",
    "Abu Arish",
    "Aziziyah",
    "Tiba",
    "Buriman",
    "Al Manar",
    "Al Muhammadiyah",
    "Al Jawharah",
    "Al Aziziyah",
    "Az Zuhur",
    "Al Jalawiyah",
    "النخيل",
    "Al Badi",
    "An Nur",
    "Uhud",
    "Al Khuzama",
    "Al Aziziyah",
    "Ishbilia",
    "الجسر",
    "Al Hamra",
    "Al Khobar Al Janubiyah",
    "Madinat Al Umal",
    "Al Hada",
    "Al Bandariyah",
    "Al Yarmouk",
    "Al Hizam Al Akhdar",
    "Ar Rawabi",
    "Al Andalus",
    "Qurtoba",
    "Dana Al Shamaliah",
    "Dana Al Janubiyah",
    "Doha Al Shamaliah",
    "Doha Al Janubiyah",
    "Aljamiah",
    "Al Qusur",
    "Tihamah",
    "Bir Uthman",
    "Ar Rayah",
    "Ad Difa",
    "Al Khalidiyyah",
    "Al Fath",
    "Al Anabis",
    "Qurban",
    "العريض",
    "Al Mubarraz",
    "Al Hofuf",
    "مدينة الجفر",
    "Alsamer",
    "Althagher",
    "Al Muntazah",
    "Alnahdah",
    "Al Quway",
    "As Safra",
    "Al Qadissya",
    "Al shamas",
    "Al Amn",
    "Al Nour",
    "Al taleem",
    "Al Manar",
    "Al Rawda",
    "Al Iskan",
    "Al Rayan",
    "Al ofg",
    "السادة",
    "As Salhiyah",
    "Al fayziyyah",
    "Algnoub",
    "As Sulimaniyah",
    "Al Mazadah",
    "As Salhiyah",
    "Ash Shuraymiyyah",
    "Alfakhrya",
    "Almanar",
    "Al Ashrafyah",
    "Alkhuzama",
    "Al olaya",
    "Badya",
    "Al Rayan",
    "Al Faidha",
    "شيخة",
    "Alhada",
    "Al matar",
    "nuzha",
    "Sultanah",
    "Al qadisiyah",
    "Al Khuzama",
    "Al Wusayta",
    "Al Mahattah",
    "Az Zahra",
    "Al Aziziyah",
    "Al Masyaf",
    "Az Zibarah",
    "Aja",
    "Maashi",
    "Al Huwaya",
    "Qurwa",
    "Asharqyyah",
    "Wadi waj",
    "Shihar",
    "Al jal",
    "Jubrah",
    "Al aqeeq",
    "Ashuhada",
    "As sadad",
    "Hawaya",
    "As salamah",
    "Al aziziyyah",
    "Al khalidiyyah",
    "Al mathnah",
    "Nakhab",
    "Ashmun",
    "Mansak",
    "AL muftaha",
    "AL Qabil",
    "Alandalus",
    "Alarin",
    "Almarooj",
    "Annasim",
    "AL Mozvin",
    "Addabab",
    "Abu Hammad",
    "Belbes",
    "Shirbin",
    "Boulaq El Dakrour",
    "El Senbellawein",
    "Damietta El Gadeeda",
    "El Salam City",
    "Badr City",
    "Shibin Al Qanater",
    "Alimosho",
    "Ajeromi-Ifelodun",
    "Kosofe",
    "Mushin",
    "Ojo",
    "Agege",
    "Ifako-Ijaye",
    "Shomolu",
    "Amuwo-Odofin",
    "Lagos Mainland",
    "Ikeja",
    "Oshodi-Isolo",
    "Apapa",
    "Eti-Osa",
    "Lagos Island",
    "Badagry",
    "Ikorodu",
    "Ibeju-Lekki",
    "Epe",
    "Al Khalidiyyah",
    "An Nasim",
    "Al Aziziyah",
    "As Suqur",
    "An Nakhil",
    "الفتح",
    "Al Rawdah",
    "AS Sadd",
    "Al Sharafiyah",
    "Shakar",
    "Al Faisaliyyah",
    "Al jame'ah",
    "Al Salam",
    "Al Aqeeq",
    "Al Shefa",
    "New Giza",
    "Al Baladiyah",
    "Abu Musa Al Ashari",
    "as Sinaiyah",
    "Ar Rabi",
    "Al Faiha",
    "Al Batin",
    "Al Rawdah",
    "Al Aziziyah",
    "Al Masif",
    "Al Muruj",
    "Al Muhammadiyah",
    "الصفاء",
    "Al Wahah",
    "Al Khalidiyah",
    "Fulaij",
    "Waly Al Ahd ",
    "Al Lith Road",
    "Al Mughaisilah",
    "Al Usbah",
    "Bani Muawiyah",
    "Al Wabra",
    "Al Mansur",
    "Al Hindawiyyah",
    "Alawali",
    "Prince Mishal District",
    "Alkhalidiyyah",
    "Al Mukhayyam",
    "Al Faisaliah",
    "Housing of Interior Security Forces",
    "Al Athaybah",
    "Dahdah",
    "Northern Al Fahd",
    "Alfahd",
    "Ad Dubat",
    "Sharq Ad Dubat",
    "Shamal Ad Dubat",
    "الاملاح",
    "Alqabil",
    "Al Jurbah",
    "Aba Lasaud",
    "Karen",
    "Kileleshwa",
    "Kilimani",
    "Kitisuru",
    "Muthaiga",
    "Nairobi CBD",
    "Upper Hill",
    "Athi River",
    "Embakasi",
    "Imara Daima",
    "Juja",
    "Kenol",
    "Kiambu",
    "Kikuyu",
    "Kitengela",
    "Komarock",
    "Langata",
    "Limuru",
    "Machakos",
    "Mountain View",
    "Muranga",
    "Nairobi West",
    "Ngara",
    "Ngong",
    "Ngumba",
    "Nyayo Highrise",
    "Pangani",
    "Rongai",
    "Ruiru",
    "South C",
    "Thika",
    "Umoja",
    "Utawala",
    "Dagoreti",
    "Dandora",
    "Eastleigh",
    "Githurai",
    "Golf Course",
    "Hamza",
    "Kahawa",
    "Kangemi",
    "Kariobangi",
    "Kawangware",
    "Kayole",
    "Pipeline",
    "Roysambu",
    "Savanna",
    "Uthiru",
    "Zimmerman",
    "Westlands",
    "Parklands-Highridge",
    "Runda-Gigiri",
    "Garden Estate-Thome",
    "Kenyatta National Hospital",
    "Kasarani-Mwiki",
    "Ngong Road",
    "Njiru-Ruai",
    "Al Hulaylah",
    "Al Badiyah",
    "Al Rakah Ash Shamaliyah",
    "Al Tubayshi",
    "Al Rakah Al Janubiyah",
    "South B",
    "Loresho",
    "Lavington",
    "Mombasa CBD",
    "Nyali",
    "Mtongwe",
    "Mtwapa",
    "Kongowea",
    "Kisauni",
    "Likoni",
    "Malindi",
    "Kilifi",
    "Kwale",
    "Ash Shara'i",
    "Ar Rashidiyyah",
    "Al Ju'ranah",
    "Al'usaylah",
    "Wadi Jalil",
    "Aga",
    "umm khalid",
    "Al Aziziyyah",
    "Dhul Hulaifah",
    "ABU kabir",
    "Mlolongo",
    "Syokimau",
    "Hurlingham",
    "Nyahururu",
    "Eldoret",
    "Baringo",
    "Nakuru",
    "Naivasha",
    "Narok",
    "Kericho",
    "Meru",
    "Embu",
    "Kitui",
    "Nyeri",
    "Kakamega",
    "Kerugoya",
    "Kirinyaga",
    "Kisumu",
    "Homabay",
    "Migori",
    "Kisii",
    "Nyamira",
    "Bungoma",
    "Ar Rahmaniyyah",
    "النهضه",
    "al qudus",
    "Al Harmin",
    "Al Salam",
    "Al Faisaliah",
    "Jabal Al Nour",
    "Al Khansa",
    "Al Adel",
    "AL Khadra",
    "Al Nuzhah",
    "Al Hamra Umm Al Jud",
    "Al Zahra",
    "Al Salamah",
    "Al Rusayfah",
    "Surulere",
    "Abeokuta North",
    "Abeokuta South",
    "Ifo",
    "Ijebu East",
    "Ijebu North",
    "Ijebu Ode",
    "Ikenne",
    "Obafemi-Owode",
    "Remo North",
    "Sagamu",
    "Ado Odo Ota"
]